version: '3'

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn RasPierreUnchained.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static_deploy
        env_file:
            - ./.env.prod
        expose:
            - 8000
        depends_on:
            - db
    
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static_deploy
        ports:
          - 80:80
        depends_on:
          - web

volumes:
  postgres_data:
  static_volume:
