version: '3'

services:

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
        ports:
            - "5432:5432" # visible from outside


    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env.dev
        ports:
            - "8000:8000"
        depends_on:
            - db
    

    backend:
        build: 
            context: scivolo
            dockerfile: Dockerfile
        container_name: "scivolo"
        volumes:
            - ./_backup:/usr/data/app/
            - ./scivolo/src:/usr/src/app
        ports:
            - 2500:2500
        env_file:
            - .env.dev
        command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 2500

    
    adminer:
        image: adminer
        ports:
            - 8080:8080
    
volumes:
  postgres_data:
