version: '3'

services:
    db:
        image: postgres:12.0-alpine
        container_name: ras_db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
        restart: unless-stopped
    
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: ras_django
        command: gunicorn RasPierreUnchained.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static_deploy
        env_file:
            - ./.env.prod
        expose:
            - 8000
        depends_on:
            - db
        restart: unless-stopped
    
    nginx:
        image: nginx:1.17-alpine
        container_name: ras_nginx
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static_deploy
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        ports:
          - 80:80
        depends_on:
          - web
        restart: unless-stopped
    
    certbot:
        image: certbot/certbot
        container_name: ras_certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on:
            - nginx
            - web
        command: certonly --webroot --webroot-path=/home/app/web --email ddeennyy@hotmail.it --agree-tos --no-eff-email --staging -d raspierre.it  -d www.raspierre.it

volumes:
  postgres_data:
  static_volume:
  certbot-etc:
  certbot-var:
