version: '3'

services:
    migration:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
    population:
        build: .
        command: python manage.py loaddata data.json
        volumes:
            - .:/usr/src/app
        depends_on:
            - migration
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - EMAIL_HOST
            - EMAIL_HOST_USER
            - EMAIL_PORT
            - EMAIL_HOST_PASSWORD
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - migration
            - population
