version: '3'

services:
    migration:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env.dev
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - EMAIL_HOST
            - EMAIL_HOST_USER
            - EMAIL_PORT
            - EMAIL_HOST_PASSWORD
        command: gunicorn RasPierreUnchained.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env.prod
        ports:
            - "8000:8000"
        depends_on:
            - migration
