# Generated by Django 3.0.3 on 2020-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('text_short', models.CharField(max_length=5000)),
                ('test_all', models.CharField(max_length=5000)),
            ],
        ),
    ]
