# Generated by Django 3.0.3 on 2020-05-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='test_all',
            new_name='text_all',
        ),
    ]
