# Generated by Django 3.0.3 on 2020-05-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0004_auto_20200517_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
