# Generated by Django 3.0.3 on 2020-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0005_auto_20200517_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text_all',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_short',
            field=models.TextField(max_length=5000),
        ),
    ]
