# Generated by Django 3.0.7 on 2020-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='distance_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='distance',
            field=models.IntegerField(blank=True),
        ),
    ]
