# Generated by Django 3.0.7 on 2020-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0003_auto_20200615_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzina', 'Benzina'), ('Elettrica', 'Elettrica')], max_length=10),
        ),
    ]
