# Generated by Django 3.0.7 on 2020-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0006_station_insertdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='distance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
