# Generated by Django 3.0.7 on 2020-06-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0007_auto_20200618_1803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('event_date', 'auto')},
        ),
    ]
