# Generated by Django 3.0.7 on 2020-11-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0008_auto_20200618_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('lap_length', models.IntegerField()),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PoolSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('lap_number', models.IntegerField()),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='alldoc.Pool')),
            ],
            options={
                'unique_together': {('event_date', 'pool')},
            },
        ),
    ]
