# Generated by Django 3.0.7 on 2020-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldoc', '0009_pool_poolsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pool',
            name='location',
        ),
    ]
