# Generated by Django 3.0.3 on 2020-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmasg', '0003_auto_20200404_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='job_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
