# Generated by Django 3.0.3 on 2020-04-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmasg', '0008_room_gift_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMessage',
        ),
    ]
