# Generated by Django 3.0.3 on 2020-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmasg', '0009_delete_roommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
